import { Inter } from 'next/font/google';

import {
  OrderEnum,
  TermObjectsConnectionOrderbyEnum,
  fetchCategories,
} from '@woographql/graphql';

import { TopNav, NavItem } from '@woographql/server/TopNav';
import { SessionProvider } from '@woographql/client/SessionProvider';
import { Toaster } from '@woographql/ui/toaster';

/* Font Awesome */
import '@fortawesome/fontawesome-free/css/fontawesome.css';
import '@fortawesome/fontawesome-free/css/brands.css';
import '@fortawesome/fontawesome-free/css/solid.css';

import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const categories = await fetchCategories(
    5,
    1,
    {
      orderby: TermObjectsConnectionOrderbyEnum.COUNT,
      order: OrderEnum.DESC
    }
  ) || [];
  const menu: NavItem[] = [
    ...categories.map((category) => ({
      label: category.name as string,
      href: `/${category.slug}`,
    })),
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <TopNav menu={menu} />
          <main className="w-full">
            {children}
          </main>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  )
}
